import pandas as pd
import plotly.express as px
import streamlit as st

st.title('Bike Sales Data Analysis')
st.write('this is the bike sales analysis')


@st.cache_data
def load_data():
    data=pd.read_csv('bike_sales.csv')
    return(data)

data=load_data()

if st.checkbox('Show raw data'):
    st.subheader('raw data')
    st.write(data)


fig=px.bar(data,x="State", y=" Revenue ",title='Bar graph of revene generated by  bike sales per state')
fig.show()
st.plotly_chart(fig)


correlation_matrix = data.corr(numeric_only=True)
fig = px.imshow(correlation_matrix, title='Correlation Matrix')
fig.show()
st.plotly_chart(fig)